### ISSUE TITLE
Zika html5 table - displaying more countries

### ISSUE THREAD

**Issue by jmealing** [gc-proto/health-1#3]
Table size restrictions are part of the WET "wb-tables" class.

Followed guides and documentation but couldn't resolve to change display. WET recommends using DataTables plugin to customize.

Require some assistance to get it working.

https://wet-boew.github.io/v4.0-ci/demos/tables/tables-en.html

**Comment by lisafast** [comment]
@steve-h suggests you take a look at the data.wb.tables js on the Departments and Agencies page. https://www.canada.ca/en/government/dept.html

**Comment by jmealing** [comment]
Super! Please thank Steve for me! Took me 5 seconds to fix once I had an example with the script modifying it.
