### ISSUE TITLE
Vaccine additives - when use details summary

### ISSUE THREAD

**Issue by lisafast** [gc-proto/health-1#6]
@quidampepin What we learned from the vaccine task is that Details summary items need to not be misleading. So if there is a list of summaries, and only the titles are there in the summary, people can be misled. 
So in the list of additives, Thimerosal as a summary item makes it look like it IS an additive. But if you click to open, you see it is NOT used as an additive anymore. 

The way we solved it in travel vaccines was to add 'recommended', 'not recommended' etc. directly into the summary. 

This is the delicate balance of details-summary. 

![image](https://user-images.githubusercontent.com/28159252/34885618-91736094-f78e-11e7-8431-c0c3c66eb910.png)

Thoughts?

**Comment by quidampepin** [comment]
I hadn't read through each one yet. In a list like that, it does suggest that it is an additive. I guess the solution to either put it in the summary (Thimerosal - generally not used), or to remove it from the list. Something to discuss this afternoon.

**Comment by quidampepin** [comment]
Let's wait and see what content HC will provide (it may or may not have the list of potential additives).
