### ISSUE TITLE
Chikungunya on Italy advisory page

### ISSUE THREAD

**Issue by jmealing** [gc-proto/health-1#8]
Italy has chikungunya in the Outbreak Monitoring tab, but there's no health travel notice for it either (which is inconsistent content, other country pages do have THN for chikungunya)

Can I remove for testing purposes as it isn't part of the testing set of Q & A?

**Comment by patlaj** [comment]
Seems like it's a mistake that Italy doesn't link to the notice...France does, and I think they're exactly the same conditions. 

Anyway, we should probably leave it how it was during the test. (Which is probably how it is now too).

**Comment by jmealing** [comment]
Guess people can type it in if they open the outbreak tab. Good to mention to the Travel/Health team they have inconsistent content with the notice.
